/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QlyBenhnhan;

import SQL.sql_Benhnhan;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author duong
 */
public class Benhnhan extends javax.swing.JFrame {

    /**
     * Creates new form Benhnhan
     */
    String Mabn;
    public Benhnhan(String Mabn){
        initComponents();
        setMabn(Mabn);
        try {
            hienthi_Pro();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Định dạng ngày không đúng", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        
        hienthi_Ba();
        hienthi_Dt();
    }

    public String getMabn() {
        return Mabn;
    }

    public void setMabn(String Mabn) {
        this.Mabn = Mabn;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_Mabn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Hoten = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Gtinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Cccd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_Bhyt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_Sdt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_Diachi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btn_Edit = new javax.swing.JButton();
        btn_Save = new javax.swing.JButton();
        btn_ChangePass = new javax.swing.JButton();
        txt_Date = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_Ba = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_Maba = new javax.swing.JTextField();
        txt_Tenbs = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_Chandoan = new javax.swing.JTextArea();
        txt_Datekham = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_Tongtien = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_Searchba = new javax.swing.JTextField();
        btn_Searchba = new javax.swing.JButton();
        btn_Skipba = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Dt = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        txt_Madt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_Thuoc = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_Searchdt = new javax.swing.JTextField();
        btn_Searchdt = new javax.swing.JButton();
        txt_Tongtiendt = new javax.swing.JTextField();
        txt_Datedt = new javax.swing.JFormattedTextField();
        btn_Skipdt = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Hồ sơ bệnh án");
        setLocation(new java.awt.Point(643, 270));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel2.setText("Mã bệnh nhân:");

        jLabel3.setText("Họ tên:");

        jLabel4.setText("Ngày sinh:");

        jLabel5.setText("Giới tính:");

        jLabel6.setText("CCCD/CMT:");

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("(*)");

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("(*)");

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("(*)");

        jLabel10.setText("BHYT:");

        jLabel11.setText("SĐT:");

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("(*)");

        jLabel13.setText("Email:");

        jLabel14.setText("Địa chỉ:");

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("(*)");

        btn_Edit.setText("Chỉnh sửa");
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });

        btn_Save.setText("Lưu");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        btn_ChangePass.setText("Đổi mật khẩu");
        btn_ChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChangePassActionPerformed(evt);
            }
        });

        txt_Date.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Edit)
                        .addGap(98, 98, 98)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Save)
                        .addGap(71, 71, 71)
                        .addComponent(btn_ChangePass))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Mabn)
                            .addComponent(txt_Hoten)
                            .addComponent(txt_Gtinh, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Cccd)
                            .addComponent(txt_Bhyt)
                            .addComponent(txt_Sdt)
                            .addComponent(txt_Email)
                            .addComponent(txt_Diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15))))
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Mabn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel8))
                    .addComponent(txt_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Gtinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_Cccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_Bhyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_Sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_Diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Edit)
                    .addComponent(btn_Save)
                    .addComponent(btn_ChangePass))
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("THÔNG TIN CÁ NHÂN    ", jPanel1);

        tb_Ba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã bệnh án", "Mã bác sĩ", "Ngày khám", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Ba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_BaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_Ba);
        if (tb_Ba.getColumnModel().getColumnCount() > 0) {
            tb_Ba.getColumnModel().getColumn(0).setResizable(false);
            tb_Ba.getColumnModel().getColumn(0).setPreferredWidth(150);
            tb_Ba.getColumnModel().getColumn(1).setResizable(false);
            tb_Ba.getColumnModel().getColumn(1).setPreferredWidth(150);
            tb_Ba.getColumnModel().getColumn(2).setResizable(false);
            tb_Ba.getColumnModel().getColumn(2).setPreferredWidth(200);
            tb_Ba.getColumnModel().getColumn(3).setResizable(false);
            tb_Ba.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        jLabel16.setText("Mã bệnh án:");

        jLabel17.setText("Tên bác sĩ:");

        jLabel18.setText("Ngày khám:");

        jLabel19.setText("Chẩn đoán");

        txt_Chandoan.setColumns(20);
        txt_Chandoan.setRows(5);
        jScrollPane3.setViewportView(txt_Chandoan);

        txt_Datekham.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jLabel20.setText("Tổng tiền:");

        jLabel21.setText("Tìm kiếm:");

        btn_Searchba.setText("Tìm kiếm");
        btn_Searchba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchbaActionPerformed(evt);
            }
        });

        btn_Skipba.setText("Bỏ qua");
        btn_Skipba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SkipbaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Datekham))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Maba, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(txt_Tenbs))))
                        .addGap(148, 148, 148)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_Searchba, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Searchba)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Skipba))
                            .addComponent(jScrollPane3))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_Maba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txt_Tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_Tenbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_Datekham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_Searchba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Searchba)
                    .addComponent(btn_Skipba))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("THÔNG TIN BỆNH ÁN     ", jPanel2);

        jPanel3.setEnabled(false);

        tb_Dt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đơn thuốc", "Ngày khám", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Dt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_DtMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Dt);
        if (tb_Dt.getColumnModel().getColumnCount() > 0) {
            tb_Dt.getColumnModel().getColumn(0).setResizable(false);
            tb_Dt.getColumnModel().getColumn(0).setPreferredWidth(150);
            tb_Dt.getColumnModel().getColumn(1).setResizable(false);
            tb_Dt.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel22.setText("Mã đơn thuốc:");

        jLabel23.setText("Ngày khám:");

        txt_Thuoc.setColumns(20);
        txt_Thuoc.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txt_Thuoc.setRows(5);
        jScrollPane5.setViewportView(txt_Thuoc);

        jLabel24.setText("Tổng tiền:");

        jLabel26.setText("Tìm kiếm:");

        btn_Searchdt.setText("Tìm kiếm");
        btn_Searchdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchdtActionPerformed(evt);
            }
        });

        txt_Datedt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        btn_Skipdt.setText("Bỏ qua");
        btn_Skipdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SkipdtActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Chi tiết đơn thuốc");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_Searchdt)
                                .addGap(30, 30, 30)
                                .addComponent(btn_Skipdt))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel26))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Searchdt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_Datedt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                        .addComponent(txt_Madt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_Tongtiendt, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25)
                                .addGap(71, 71, 71))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txt_Madt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txt_Datedt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txt_Tongtiendt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Searchdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Searchdt)
                            .addComponent(btn_Skipdt))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("THÔNG TIN ĐƠN THUỐC", jPanel3);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("HỒ SƠ BỆNH ÁN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(212, 212, 212)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hienthi_Pro() throws ParseException{
        ArrayList<String> ht_Pro = new sql_Benhnhan(Mabn).hienthi_Pro();
        txt_Mabn.setText(Mabn);
        txt_Hoten.setText(ht_Pro.get(0));
        txt_Gtinh.setText(ht_Pro.get(1));
        
        txt_Date.setDate(new SimpleDateFormat("dd/MM/yyyy").parse(ht_Pro.get(2)));
        
        txt_Cccd.setText(ht_Pro.get(3));
        txt_Bhyt.setText(ht_Pro.get(4));
        txt_Sdt.setText(ht_Pro.get(5));
        txt_Email.setText(ht_Pro.get(6));
        txt_Diachi.setText(ht_Pro.get(7));  
        
        txt_Hoten.setEditable(false);
        txt_Gtinh.setEditable(false);
        txt_Date.setEnabled(false);
        txt_Cccd.setEditable(false);
        txt_Bhyt.setEditable(false);
        txt_Sdt.setEditable(false);
        txt_Email.setEditable(false);
        txt_Diachi.setEditable(false);
        btn_Save.setEnabled(false);
    }
    
    private void hienthi_Ba(){
        DefaultTableModel model = (DefaultTableModel) tb_Ba.getModel();
        model.getDataVector().clear();
        ArrayList<ArrayList<Object>> ht_Ba = new sql_Benhnhan(Mabn).hienthi_Ba();
        
        for (ArrayList<Object> x : ht_Ba) {
            model.addRow(x.toArray());
        }
        txt_Maba.setText("");
        txt_Tenbs.setText("");
        txt_Datekham.setText("");
        txt_Chandoan.setText("");
        txt_Tongtien.setText("");
        txt_Searchba.setText("");
        tb_Ba.clearSelection();
        txt_Maba.setEditable(false);
        txt_Tenbs.setEditable(false);
        txt_Datekham.setEditable(false);
        txt_Chandoan.setEditable(false);
        txt_Tongtien.setEditable(false);
        btn_Searchba.setEnabled(true);
    }
    
    private void hienthi_Dt(){
        DefaultTableModel model = (DefaultTableModel) tb_Dt.getModel();
        model.getDataVector().clear();
        
        ArrayList<ArrayList<Object>> ht_Dt = new sql_Benhnhan(Mabn).hienthi_Dt();
        
        for (ArrayList<Object> x : ht_Dt) {
            model.addRow(x.toArray());
        }
        
        txt_Madt.setText("");
        txt_Datedt.setText("");
        txt_Thuoc.setText("");
        txt_Tongtiendt.setText("");
        txt_Searchdt.setText("");
        tb_Dt.clearSelection();
        txt_Madt.setEditable(false);
        txt_Datedt.setEditable(false);
        txt_Thuoc.setEditable(false);
        txt_Tongtiendt.setEditable(false);
        btn_Searchdt.setEnabled(true);
    }
    
    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
        // TODO add your handling code here:
        txt_Hoten.setEditable(true);
        txt_Date.setEnabled(true);
        txt_Cccd.setEditable(true);
        txt_Bhyt.setEditable(true);
        txt_Sdt.setEditable(true);
        txt_Email.setEditable(true);
        txt_Diachi.setEditable(true);
        btn_Edit.setEnabled(false);
        btn_Save.setEnabled(true);
    }//GEN-LAST:event_btn_EditActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed

        new sql_Benhnhan(Mabn).Save(txt_Hoten.getText(), txt_Date.getDate(), txt_Cccd.getText(), txt_Bhyt.getText(), txt_Cccd.getText(), txt_Email.getText(), txt_Diachi.getText());
        try {
            hienthi_Pro();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Định dạng ngày không đúng", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        
        txt_Hoten.setEditable(false);
        txt_Date.setEnabled(false);
        txt_Cccd.setEditable(false);
        txt_Bhyt.setEditable(false);
        txt_Sdt.setEditable(false);
        txt_Email.setEditable(false);
        txt_Diachi.setEditable(false);
        btn_Edit.setEnabled(true);
        btn_Save.setEnabled(false);
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void btn_ChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChangePassActionPerformed
        new ChangePass(this).setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btn_ChangePassActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn thoát chương trình?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)){
            this.setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btn_SkipbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SkipbaActionPerformed
        hienthi_Ba();
    }//GEN-LAST:event_btn_SkipbaActionPerformed

    private void tb_BaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_BaMouseClicked
        // TODO add your handling code here:
        if(tb_Ba.getSelectedRowCount() > 0){
            txt_Maba.setText((String) tb_Ba.getValueAt(tb_Ba.getSelectedRow(), 0));
            txt_Datekham.setText((String) tb_Ba.getValueAt(tb_Ba.getSelectedRow(), 2));
            txt_Tongtien.setText((String) tb_Ba.getValueAt(tb_Ba.getSelectedRow(), 3));
            
            ArrayList<String> click_Ba = new sql_Benhnhan(Mabn).click_Ba(txt_Maba.getText());
            txt_Tenbs.setText(click_Ba.get(0));
            txt_Chandoan.setText(click_Ba.get(1));
            
            btn_Searchba.setEnabled(false);
        }   
    }//GEN-LAST:event_tb_BaMouseClicked

    private void btn_SearchbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchbaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tb_Ba.getModel();
        model.getDataVector().clear();
        ArrayList<ArrayList<Object>> sr_Ba = new sql_Benhnhan(Mabn).hienthi_SearchBa(txt_Searchba.getText());

        if(sr_Ba != null){
            for (ArrayList<Object> x : sr_Ba) {
                model.addRow(x.toArray());
            }
        }
        else{
            model.fireTableDataChanged();
        }
        txt_Searchba.setText("");
    }//GEN-LAST:event_btn_SearchbaActionPerformed

    private void btn_SkipdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SkipdtActionPerformed
        // TODO add your handling code here:
        hienthi_Dt();
    }//GEN-LAST:event_btn_SkipdtActionPerformed

    private void tb_DtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_DtMouseClicked
        
        txt_Thuoc.setText("");
        if (tb_Dt.getSelectedRowCount() > 0){
            txt_Madt.setText((String) tb_Dt.getValueAt(tb_Dt.getSelectedRow(), 0));
            txt_Datedt.setText((String) tb_Dt.getValueAt(tb_Dt.getSelectedRow(), 1));
            txt_Tongtiendt.setText((String) tb_Dt.getValueAt(tb_Dt.getSelectedRow(), 2));

            String Madt = (String) tb_Dt.getValueAt(tb_Dt.getSelectedRow(), 0);
            txt_Thuoc.setText(String.format("|%-15s|%-10s|%n", "Tên thuốc", "SL"));
            ArrayList<ArrayList<Object>> click_Dt;

            click_Dt = new sql_Benhnhan(Mabn).click_Dt(Madt);
            for (ArrayList<Object> x : click_Dt) {
                txt_Thuoc.setText(txt_Thuoc.getText() + String.format("|%15s|%10s|%n", x.get(0), x.get(1)));
            }
        }
        btn_Searchdt.setEnabled(false);     
    }//GEN-LAST:event_tb_DtMouseClicked

    private void btn_SearchdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchdtActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tb_Dt.getModel();
        model.getDataVector().clear();

        ArrayList<ArrayList<Object>> sr_Dt = new sql_Benhnhan(Mabn).hienthi_SearchDt(txt_Searchdt.getText());

        if(sr_Dt != null){
            for (ArrayList<Object> x : sr_Dt) {
                model.addRow(x.toArray());
            }
        }
        else{
            model.fireTableDataChanged();
        }
        txt_Searchdt.setText("");
    }//GEN-LAST:event_btn_SearchdtActionPerformed

    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Benhnhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Benhnhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Benhnhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Benhnhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Benhnhan().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ChangePass;
    private javax.swing.JButton btn_Edit;
    private javax.swing.JButton btn_Save;
    private javax.swing.JButton btn_Searchba;
    private javax.swing.JButton btn_Searchdt;
    private javax.swing.JButton btn_Skipba;
    private javax.swing.JButton btn_Skipdt;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tb_Ba;
    private javax.swing.JTable tb_Dt;
    private javax.swing.JTextField txt_Bhyt;
    private javax.swing.JTextField txt_Cccd;
    private javax.swing.JTextArea txt_Chandoan;
    private com.toedter.calendar.JDateChooser txt_Date;
    private javax.swing.JFormattedTextField txt_Datedt;
    private javax.swing.JFormattedTextField txt_Datekham;
    private javax.swing.JTextField txt_Diachi;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Gtinh;
    private javax.swing.JTextField txt_Hoten;
    private javax.swing.JTextField txt_Maba;
    private javax.swing.JTextField txt_Mabn;
    private javax.swing.JTextField txt_Madt;
    private javax.swing.JTextField txt_Sdt;
    private javax.swing.JTextField txt_Searchba;
    private javax.swing.JTextField txt_Searchdt;
    private javax.swing.JTextField txt_Tenbs;
    private javax.swing.JTextArea txt_Thuoc;
    private javax.swing.JTextField txt_Tongtien;
    private javax.swing.JTextField txt_Tongtiendt;
    // End of variables declaration//GEN-END:variables
}
